import { useEffect, useState } from 'react';
import { Activity, FileText, Loader2, Sparkles, X } from 'lucide-react';
import type { DocumentRecord } from '../types';
import { formatBytes } from '../lib/format';
import { listDocumentActivities, type DocumentActivity } from '../lib/documents';
export function DocumentDetailModal({ document, onClose }: { document?: DocumentRecord; onClose: () => void }) {
  const [activities, setActivities] = useState<DocumentActivity[]>([]); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!document) return; setLoading(true); void listDocumentActivities(document.id).then(setActivities).catch(() => setActivities([])).finally(() => setLoading(false)); }, [document]);
  if (!document) return null;
  const rows = [['Type', document.file_type.toUpperCase()], ['Size', formatBytes(document.file_size)], ['Status', document.processing_status], ['Chunks', String(document.chunk_count)], ['Created', new Date(document.created_at).toLocaleString()], ['Folder', document.category || 'Uncategorized']];
  return <div className="fixed inset-0 z-50 flex items-end bg-black/70 p-0 sm:items-center sm:justify-center sm:p-4"><div className="glass w-full max-w-xl rounded-t-2xl border border-white/15 p-5 shadow-2xl sm:rounded-2xl"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="rounded-xl bg-brand-500/15 p-2 text-brand-300"><FileText size={20}/></span><div><h3 className="text-base font-semibold text-white">Document details</h3><p className="mt-1 max-w-[280px] truncate text-xs text-ink-500">{document.file_name}</p></div></div><button onClick={onClose} className="text-ink-400 hover:text-white"><X size={18}/></button></div><div className="mt-5 grid grid-cols-2 gap-2">{rows.map(([label, value]) => <div key={label} className="rounded-lg border border-white/10 bg-black/10 p-3"><p className="text-[10px] uppercase tracking-wider text-ink-600">{label}</p><p className="mt-1 truncate text-xs text-ink-200">{value}</p></div>)}</div><div className="mt-4"><p className="text-xs font-medium text-ink-300">Tags</p><div className="mt-2 flex flex-wrap gap-1.5">{document.tags?.length ? document.tags.map((tag) => <span key={tag} className="rounded bg-white/5 px-2 py-1 text-[11px] text-ink-300">#{tag}</span>) : <span className="text-xs text-ink-600">No tags</span>}</div></div><div className="mt-5 border-t border-white/10 pt-4"><p className="flex items-center gap-2 text-xs font-medium text-ink-300"><Activity size={14}/> Activity timeline</p>{loading ? <Loader2 size={16} className="mt-3 animate-spin text-brand-400"/> : <div className="mt-3 max-h-44 overflow-auto pr-1">{activities.length ? <ol className="space-y-3">{activities.map((item, index) => <li key={item.id} className="relative pl-5"><span className="absolute left-[2px] top-1.5 h-2.5 w-2.5 rounded-full bg-brand-400 ring-4 ring-brand-500/10" />{index < activities.length - 1 && <span className="absolute left-[7px] top-4 h-full w-px bg-white/10" />}<div className="rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2"><div className="flex items-center justify-between gap-3"><p className="inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wider text-brand-300"><Sparkles size={11} />{item.action}</p><span className="text-[10px] text-ink-600">{new Date(item.created_at).toLocaleString()}</span></div><p className="mt-1 text-[11px] leading-relaxed text-ink-400">{item.details?.fileName ? `File: ${item.details.fileName}` : 'Activity recorded automatically by the database trigger.'}</p></div></li>)}</ol> : <p className="rounded-xl border border-dashed border-white/10 bg-white/[0.02] px-4 py-5 text-center text-xs text-ink-600">No recorded activity yet.</p>}</div>}</div></div></div>;
}
