-- Vector storage for n8n only. Keep this separate from public.documents,
-- which is the application's document-library metadata table.
create extension if not exists vector with schema extensions;

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  content text,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(3072)
);

create index if not exists document_chunks_metadata_idx
  on public.document_chunks using gin (metadata);

alter table public.document_chunks enable row level security;

-- The browser has no access to raw chunk content. n8n uses a service-role
-- Supabase credential, which bypasses RLS, to insert and retrieve chunks.

create or replace function public.match_document_chunks(
  query_embedding extensions.vector(3072),
  match_count integer default 3,
  filter jsonb default '{}'::jsonb
)
returns table (id bigint, content text, metadata jsonb, similarity real)
language sql
stable
set search_path = public, extensions
as $$
  select
    document_chunks.id,
    document_chunks.content,
    document_chunks.metadata,
    1 - (document_chunks.embedding <=> query_embedding) as similarity
  from public.document_chunks
  where document_chunks.metadata @> filter
  order by document_chunks.embedding <=> query_embedding
  limit match_count;
$$;

revoke all on function public.match_document_chunks(extensions.vector, integer, jsonb) from public, anon, authenticated;
grant execute on function public.match_document_chunks(extensions.vector, integer, jsonb) to service_role;
